#!/bin/bash

set_default_editor() {
    sudo apt-get install vim -y
    git config --global core.editor 'vim'
    echo 'export EDITOR=vim' >> ~/.bashrc
    echo 'export VISUAL=vim' >> ~/.bashrc
    source $HOME/.bashrc
}

main() {
    install_aws_cli
    set_default_editor
}

main
