#!/bin/bash

install_aws_cli() {
    curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
    unzip awscliv2.zip
    sudo ./aws/install
}

set_default_editor() {
    sudo apt-get install vim -y
    git config --global core.editor 'vim'
    echo 'export EDITOR=vim' >> ~/.bashrc
    echo 'export VISUAL=vim' >> ~/.bashrc
    source $HOME/.bashrc
}

main() {
    install_aws_cli
    set_default_editor
}

main
