name: Deploy Server using CodeDeploy
on:
  workflow_call:
    inputs:
      container_name:
        description: "name of container"
        type: string
        required: true
      image_url:
        description: "image url"
        type: string
        required: true
      task_definition_path:
        description: "Task defintion relative path. eg: ./.aws/task-definition.json"
        type: string
        required: true
      cluster_name:
        description: "Cluster name of the ECS cluster"
        type: string
        required: true
      service_name:
        description: "Service name of the ECS service"
        type: string
        required: true
      aws_role_to_assume:
        description: "AWS role to assume"
        type: string
        required: true
      use_sidecar:
        description: "Whether to use sidecar container"
        type: boolean
        required: false
      sidecar_container_name:
        description: "name of sidecar container"
        type: string
        required: false
      sidecar_image_url:
        description: "sidecar image url"
        type: string
        required: false
      use_codedeploy:
        description: "Legacy support placeholder"
        type: boolean
        required: true
env:
  AWS_AUDIENCE: "sts.amazonaws.com"
permissions:
  contents: read
  packages: write
  actions: write
  id-token: write
jobs:
  invoke_deployment:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v4
        with:
          repository: ${{ github.repository }}
          sparse-checkout: |
            .github/
            .envs/
            .aws/
            scripts/
      - id: install-aws-cli
        uses: unfor19/install-aws-cli-action@v1
        with:
          arch: amd64
      - uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ inputs.aws_role_to_assume }}
          audience: ${{ env.AWS_AUDIENCE }}
          aws-region: ap-northeast-2
      - name: Render Task Defintion
        uses: aws-actions/amazon-ecs-render-task-definition@v1.8.1
        id: render_task_definition
        with:
          task-definition: ${{ inputs.task_definition_path }}
          container-name: ${{ inputs.container_name }}
          image: ${{ inputs.image_url }}:${{ github.sha }}
      - name: Render Sidecar Task Defintion
        if: ${{ inputs.use_sidecar }}
        uses: aws-actions/amazon-ecs-render-task-definition@v1.8.1
        id: render_sidecar_task_definition
        with:
          task-definition: ${{ inputs.task_definition_path }}
          container-name: ${{ inputs.sidecar_container_name }}
          image: ${{ inputs.sidecar_image_url }}:${{ github.sha }}
      - name: Deploy Server without CodeDeploy
        uses: aws-actions/amazon-ecs-deploy-task-definition@v2.3.0
        if: ${{ !inputs.use_codedeploy }}
        with:
          service: ${{ inputs.service_name }}
          cluster: ${{ inputs.cluster_name }}
          task-definition: ${{ steps.render_task_definition.outputs.task-definition }}
          wait-for-service-stability: true
